# Generated by Django 4.0 on 2022-01-25 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 13, 9, 45, 118652, tzinfo=utc)),
        ),
    ]
