# Generated by Django 4.0 on 2022-01-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='store',
        ),
    ]
