# Generated by Django 4.0 on 2022-01-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_price'),
        ('orders', '0010_alter_orderitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(through='orders.OrderItem', to='shop.Product'),
        ),
    ]
